### ISSUE TITLE
PHPUnit 6.0

### ISSUE THREAD

**Issue by hiddewie** [fiunchinho/phpunit-randomizer#20]
PHPUnit 6.0 has been released.

One of the large changes is that classes do not use the `_` namespace separator, but rather the PSR `\` namespace separator. (See https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md). 

This breaks the usages of PHPUnit-randomizer where the old classes are imported. Would you accept a PR which uses the new classes, and release a new version of your randomizer? Most of the namespaced classes are in use since somewhere around PHPUnit 5.4.

**Comment by fiunchinho** [comment]
Sure. Create the PR and I'll merge it. Thank you very much for your help!!

**Comment by hiddewie** [comment]
Great! See the PR.
