### ISSUE TITLE
You don't need this - There is a default PHPUnit feature --order-by=random

### ISSUE THREAD

**Issue by ruudk** [fiunchinho/phpunit-randomizer#30]
For everybody that finds this repo and wants to try it out: you don't need this. 

You can run the following:
```
vendor/bin/phpunit --order-by=random
```

To the author: It would be great if you could change the readme of this project to say it's not needed anymore, because PHPUnit has an `--order-by=random` feature.

Best,

Ruud

**Comment by fiunchinho** [comment]
Nice! Can you send me a link to the PHPUnit docs where this is documented? Thanks!

**Comment by ruudk** [comment]
Can't find the docs, but this is the release: https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-7.3.md#730---2018-08-03

It also supports fixing the seed by doing this:

```
SEED=$(head -200 /dev/urandom | cksum | cut -f1 -d " ")
echo "Running tests with seed $SEED"
vendor/bin/phpunit --order-by=random --random-order-seed=$SEED
```
